[tool.black]
line-length = 100
skip-string-normalization = true
force-exclude = "LICENSE|requirements.txt|pyproject.toml|README.md"

[tool.pytest.ini_options]
asyncio_mode = "strict"
testpaths = [
    "tests",
]
addopts = "--import-mode=importlib"

[tool.pyright]
typeCheckingMode = "strict"
reportUnnecessaryTypeIgnoreComment = "warning"
reportUnusedImport = "error"
pythonVersion = "3.8"